# Generated by Django 5.1 on 2025-09-11 10:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('contact', models.CharField(max_length=255, verbose_name='اطلاعات تماس')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/', verbose_name='ضمیمه')),
                ('status', models.CharField(choices=[('PENDING', 'در حال بررسی'), ('IN_PROGRESS', 'در حال پیگیری'), ('RESOLVED', 'حل شده'), ('CLOSED', 'بسته شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حل شدن')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تیکت پشتیبانی',
                'verbose_name_plural': 'تیکت\u200cهای پشتیبانی',
                'ordering': ['-created_at'],
            },
        ),
    ]
