# Generated by Django 5.1 on 2025-10-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(default='USD', max_length=10)),
                ('to_currency', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('provider', models.CharField(max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['from_currency', 'to_currency', '-fetched_at'], name='core_exchan_from_cu_e4a735_idx')],
                'unique_together': {('from_currency', 'to_currency', 'provider', 'fetched_at')},
            },
        ),
    ]
