# Generated by Django 5.1 on 2025-10-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='تنظیمات سایت', help_text='نام تنظیمات', max_length=100)),
                ('card_to_card_enabled', models.BooleanField(default=True, help_text='آیا پرداخت کارت به کارت در صفحه checkout نمایش داده شود؟', verbose_name='فعال\u200cسازی پرداخت کارت به کارت')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='فعال\u200cسازی حالت نگهداری سایت', verbose_name='حالت نگهداری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
