# Safe migration for production - handles existing columns gracefully
# Generated by Django 5.1 on 2025-10-04 09:00

from django.db import migrations, models


def safe_add_order_fields(apps, schema_editor):
    """
    Safely add fields to Order model without causing duplicate column errors.
    This function checks if columns exist before adding them.
    """
    
    with schema_editor.connection.cursor() as cursor:
        
        # Check and add tracking_code field
        try:
            cursor.execute("SELECT tracking_code FROM core_order LIMIT 1")
            # Column exists, skip
        except Exception:
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE core_order 
                ADD COLUMN tracking_code VARCHAR(100) NULL
            """)
        
        # Check and add note field  
        try:
            cursor.execute("SELECT note FROM core_order LIMIT 1")
            # Column exists, skip
        except Exception:
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE core_order 
                ADD COLUMN note TEXT NULL
            """)
        
        # Check and add updated_at field
        try:
            cursor.execute("SELECT updated_at FROM core_order LIMIT 1")
            # Column exists, skip  
        except Exception:
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE core_order 
                ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW()
            """)


def reverse_add_order_fields(apps, schema_editor):
    """
    Reverse the migration by removing the added fields.
    """
    with schema_editor.connection.cursor() as cursor:
        try:
            cursor.execute("ALTER TABLE core_order DROP COLUMN IF EXISTS tracking_code")
            cursor.execute("ALTER TABLE core_order DROP COLUMN IF EXISTS note")  
            cursor.execute("ALTER TABLE core_order DROP COLUMN IF EXISTS updated_at")
        except Exception:
            # Ignore errors during reverse - fields might not exist
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings'),
    ]

    operations = [
        # Update model metadata (always safe)
        migrations.AlterModelOptions(
            name='order',
            options={
                'ordering': ['-created_at'], 
                'verbose_name': 'سفارش', 
                'verbose_name_plural': 'سفارشات'
            },
        ),
        
        # Safely add fields using custom SQL
        migrations.RunPython(
            safe_add_order_fields,
            reverse_add_order_fields
        ),
    ]