# Generated by Django 5.1 on 2025-09-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='guest_subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
