# Generated by Django 5.1 on 2025-09-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_guest_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='مسدود شده توسط پشتیبان'),
        ),
    ]
